"""entradas del perfil

Revision ID: 34384c66d52f
Revises: f7306c7c7e13
Create Date: 2026-09-30 19:34:25.429821

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34384c66d52f"
down_revision: str | Sequence[str] | None = "f7306c7c7e13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_entries",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("organization", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('experience', 'education', 'project', 'certification')",
            name=op.f("ck_profile_entries_kind"),
        ),
        sa.CheckConstraint(
            "NOT (is_current AND end_date IS NOT NULL)",
            name=op.f("ck_profile_entries_current_has_no_end"),
        ),
        sa.CheckConstraint(
            "char_length(description) <= 2000",
            name=op.f("ck_profile_entries_description_length"),
        ),
        sa.CheckConstraint(
            "start_date IS NULL OR end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_profile_entries_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_entries_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_entries")),
    )
    op.create_index(
        "ix_profile_entries_profile_id_kind",
        "profile_entries",
        ["profile_id", "kind", "position"],
        unique=False,
    )
    op.create_table(
        "profile_entry_bullets",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "char_length(text) BETWEEN 1 AND 500",
            name=op.f("ck_profile_entry_bullets_text_length"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["profile_entries.id"],
            name=op.f("fk_profile_entry_bullets_entry_id_profile_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_entry_bullets")),
    )
    op.create_index(
        "ix_profile_entry_bullets_entry_id",
        "profile_entry_bullets",
        ["entry_id", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_profile_entry_bullets_entry_id", table_name="profile_entry_bullets"
    )
    op.drop_table("profile_entry_bullets")
    op.drop_index("ix_profile_entries_profile_id_kind", table_name="profile_entries")
    op.drop_table("profile_entries")
    # ### end Alembic commands ###
