"""habilidades e idiomas del perfil

Revision ID: 45ae31d1380c
Revises: 34384c66d52f
Create Date: 2026-09-30 20:02:44.705350

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45ae31d1380c"
down_revision: str | Sequence[str] | None = "34384c66d52f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_languages",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=100), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "level IN ('a1', 'a2', 'b1', 'b2', 'c1', 'c2', 'native')",
            name=op.f("ck_profile_languages_level"),
        ),
        sa.CheckConstraint(
            "char_length(language) >= 1",
            name=op.f("ck_profile_languages_language_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_languages_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_languages")),
    )
    op.create_index(
        "uq_profile_languages_profile_id_language",
        "profile_languages",
        ["profile_id", sa.literal_column("lower(language)")],
        unique=True,
    )
    op.create_table(
        "profile_skills",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "level IN ('basic', 'intermediate', 'advanced', 'expert')",
            name=op.f("ck_profile_skills_level"),
        ),
        sa.CheckConstraint(
            "char_length(name) >= 1", name=op.f("ck_profile_skills_name_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_skills_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_skills")),
    )
    op.create_index(
        "uq_profile_skills_profile_id_name",
        "profile_skills",
        ["profile_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_profile_skills_profile_id_name", table_name="profile_skills")
    op.drop_table("profile_skills")
    op.drop_index(
        "uq_profile_languages_profile_id_language", table_name="profile_languages"
    )
    op.drop_table("profile_languages")
    # ### end Alembic commands ###
