"""documentos generados

Revision ID: 9ee51b6bc414
Revises: 45ae31d1380c
Create Date: 2026-10-01 08:40:28.726803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ee51b6bc414"
down_revision: str | Sequence[str] | None = "45ae31d1380c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("template", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("language", sa.String(length=2), nullable=True)
    )
    op.add_column(
        "documents",
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "documents", sa.Column("error_code", sa.String(length=50), nullable=True)
    )
    op.create_index(
        "ix_documents_pending_updated_at",
        "documents",
        ["updated_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###
    # Autogenerate no incluye los CHECK al modificar una tabla (trampa de
    # CLAUDE.md). Valores de DocumentErrorCode congelados aquí. Hasta F14 solo hay
    # documentos subidos y todos `ready`: ninguna fila existente los incumple.
    op.create_check_constraint(
        op.f("ck_documents_error_code"),
        "documents",
        "error_code IN ('render_failed', 'storage_limit_reached')",
    )
    op.create_check_constraint(
        op.f("ck_documents_content_matches_origin"),
        "documents",
        "(origin = 'uploaded' AND "
        "template IS NULL AND language IS NULL AND content IS NULL) OR "
        "(origin <> 'uploaded' AND "
        "template IS NOT NULL AND language IS NOT NULL AND content IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_documents_error_code_only_when_failed"),
        "documents",
        "(status = 'failed') = (error_code IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        op.f("ck_documents_error_code_only_when_failed"), "documents", type_="check"
    )
    op.drop_constraint(
        op.f("ck_documents_content_matches_origin"), "documents", type_="check"
    )
    op.drop_constraint(op.f("ck_documents_error_code"), "documents", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_documents_pending_updated_at",
        table_name="documents",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_column("documents", "error_code")
    op.drop_column("documents", "content")
    op.drop_column("documents", "language")
    op.drop_column("documents", "template")
    # ### end Alembic commands ###
